### ISSUE TITLE
Firefox 57

### ISSUE THREAD

**Issue by AZimmerhofer** [feinstaub/webextension_local_filesystem_links#95]
Hello,

Firefox 57 will need a new architecture of plugins. Are you planning to write a new compatible plugin? https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

Kind regards
Alex

**Comment by AWolf81** [comment]
Hi Alex, 

yes, we're planning to write a compatible plugin but it's not that easy to create. Most content scripts can be ported but file handling is totally different.

For more details please have a look at issue #81.

We can keep this open for other users, so the info can be found easily.

I know that the addon is already disabled in FF but it's possible to re-enable it until version 57.

Yesterday I made some progress in the prototype. Link opening & revealing is working  (tested in Windows). Next I have to add whitelisting. 

Once the core features of the prototype are ready. I have to check with @Feinstaub how we'll do the change - renaming this repo or creating a new repository.

I think it would be the best to create a new repository and name it like "webextension_local_filesystem_links". (Webextensions should also work in Chrome with small changes - so no browser name in the name of the repo. )

I wouldn't fork the prototype because I like to simplify the build setup.

Best regards
Alex

**Comment by feinstaub** [comment]
Let's use this thread for a general user-centric discussions and #81 for the technical issues.

I renamed the repo as suggested. This way, we can keep all the history.

**Comment by AZimmerhofer** [comment]
Thanks for your fast answer! Great, that you are working on it! Alex

**Comment by AZimmerhofer** [comment]
Hi @feinstaub 

any news here? Firefox 57 was released.
Kind regards
Alex

**Comment by feinstaub** [comment]
Hello Alex Z., no news yet. At least from my side. Do you have any news, @AWolf81?

**Comment by nm079** [comment]
Hi guys - really would love to know a timeline for this to be made Firefox 57 ready.

If we're talking a week or two I and my users can probably limp along, however if we're talking months or no defined time frame I may need to switch everyone over to Chrome using Local Explorer.

**Comment by PeterZamudio** [comment]
Hello, My team of 15 are all waiting and hoping you will succeed. I am bouncing them back to 56 till I hear some good news.
Good luck and thanks.

**Comment by AWolf81** [comment]
Sorry, I'm pretty busy at the moment. So it's not ready yet.

Basic functionality is working. Clicking links to open + the icon to reveal the folder. White listing needs to be improved. 

Currently just in Window OS tested. Also installer for native app not created yet but I think there are tools that can help to do that. 
Does anybody know a good installer for a python script (similar to [squirrel for windows desktop apps](https://github.com/Squirrel/Squirrel.Windows))? It should create an executable of the script and run a batch file to add some registry keys.

Time schedule - one to two weeks is realistic. I can not promise but I'll try my best.

**Comment by MurzNN** [comment]
We can review new [Open With](https://addons.mozilla.org/en-US/firefox/addon/open-with/) addon version how it works with Webextensions, and got some ideas to our extension.

**Comment by vielfrass2017** [comment]
Hi AWolf81, 
we are also appreciating your great work and looking forward for your upgrade. 

Regards

**Comment by AWolf81** [comment]
I'd like to give a status update here:
- Open & reveal is working (in browser open not added yet - will be added later)
- Whitelist setting is working (but with different patterns than before e.g. `*://localhost/*`)

@feinstaub During my testing I've noticed that we're needing an extension id, do we have an official id? At the moment, I'm using a string for testing.

So still a lot to-do and I do my best to get it ready as soon as possible. But I'm happy that the most important parts are already working.

**Todos:**
- [ ] Check if multiple whitelist patterns are working as expected
- [ ] Improve settings page
- [ ] Add executable file option to settings page
- [ ] Improve updating of new settings (e.g. whitelist should update open tabs if not matching anymore)
- [ ] Error message of file not found not correct (file name misssing)
- [ ] Update button in menu bar to show (active/inactive) + easier access to settings page.
- [ ] Create a feature list for the features that will be available in the next version (so it's easier to track what's missing)

- [ ] Create installer for native script (install python script as exe & add registry entry)
- [ ] Check extension under Linux
- [ ] Create a first version of the extension as zip-file to share for testing
- [ ] Add unit tests for Javascript & Python

**Comment by feinstaub** [comment]
Hi @AWolf81. Thanks for the status update. From the current package.json, I took this ID:

jid1-JAzC7z53jemo5Q@jetpack

Is this usable for the new addon?

**Comment by AWolf81** [comment]
@feinstaub That ID looks OK. I'll add it. Thanks. I've also read something about it in a [post](https://discourse.mozilla.org/t/porting-addon-sdk-to-webextensions-getting-error-due-to-id-in-manifest-reading-manifest-error-processing-applications-gecko-id/18486). (Similar question - the mentioned error there is probably a different issue.)

**Comment by DaZeller** [comment]
Hello all,
I would also declare my interest in the Firefox57 ready AddOn.
I'm using the AddOn since mor than a year in cojunction with TiddlyWiki which is a perfect fit.

Big Thanks to the developers!!

BR Michael

**Comment by FransGoos** [comment]
dear addon developers,
I have read the discussion.
Good work are you doing.
I hope that this addon is available in the nearby future for firefox 57 (this year?)
Best regards Frans

**Comment by AWolf81** [comment]
@FransGoos
Yes, I think it could be ready this year depending on how fast the review at Mozilla is working (usually that doesn't take that long - a few days) and if we have some feedback from testers before publishing.

I'd like to have more testers because the change is pretty large.

**Current status**
PR #97 will be merged soon. After merging the `migration-branch` to master it would be great if more people could test the extension before publishing to Mozilla store. 
We'll create a package that can be downloaded and temporarily installed (as described [here](https://blog.mozilla.org/addons/2015/12/23/loading-temporary-add-ons/)) - download link will be added here.

@sweoggy Do you have time to take a quick look at the extension? Please also check if installation of native app is easy enough? (For Windows it's really easy. For Linux it is slightly more difficult but should be OK.)

**Available Features (for release 0.99.57)**
- Native app for link opening (wasn't required in previous versions - currently supported OS are **Windows & Linux**) - requires manual installation (download link see post-installation page of the extension)
- Link opening & revealing (same as before)
- White-list urls (match pattern slightly different - see info in post-install guide)
- Prevention of executable link execution (some improvements for Windows req. - .msi files can be opened)
- Activity indication with addonbar icon
- Addon-bar menu for faster access to settings
- Settings page (almost as before)
- UNC links are supported e.g. //servename/directory (SMB protocoll still not implemented but should be possible now) - root directory issue still present as reported in issue #90. More investigation required.)

**Missing features & improvements (added in future release)**
- [MISSING]: Native app support for MacOS (extension not usable at MacOS with-out the app - probably easy to implement but I don't have access to a test setup with that OS. Still trying to install OSx in VM ware.)
- [MISSING]: Right click context menu
- [MISSING]: Link text selection open via context menu
-  [MISSING]: In browser opening option (e.g. show supported types directly in Firefox like images, PDFs,...)
-  [IMPROVE]: Settings changes may require a page reload (not immediately applied e.g. changing icon option)
- [IMPROVE]: Check UNC root-level support & add SMB support (if possible)
- [IMPROVE] settings page styling (I'd like to use Firefox styling)
- [IMPROVE] executable check for Windows (msi files are also executables)

@feinstaub Is something missing in my feature list here? But I think I've mentioned everything.

If a important feature is missing please let me know.

**Comment by PeterZamudio** [comment]
Hi to all
I would be glad to test the Extention and report back if it helps you.
thanks and all the best
Peter

**Comment by AWolf81** [comment]
@PeterZamudio Thanks for your support, it would be great to get a feedback to the extension. It's now available for download (see updated comment above).

After we have some feedback we'll start the review process at Mozilla gallery to get the extension into the store.

I'm also doing more tests because at Feinstaub's installation there was something not working as expected and I need to check that issue.

If there are any issues with the extension during your test, please report it here and also write your operating system & version - then it's easier to fix the problem.

**Comment by AZimmerhofer** [comment]
@AWolf81 
Hi,
I would like to test your plugin, but cannot download it via Google Drive. Is the link broken?
Alex

**Comment by AZimmerhofer** [comment]
Hi @AWolf81 ,
I tried to load your RC1... Installing it temporarily FF shows: There was an error during installation: Directory C:\Users\xxx\Downloads does not contain a valid install manifest. FF 57.0.2 (64-bit).

**Comment by PeterZamudio** [comment]
@AWolf81
I am using Windows 10 Version 1703 and Firefox Quantum 57.0.
The local setup is local Intranet with an Apache Server and Wordpress Webpages
The Add-On loaded OK over Debugging and I can access the options page no problem.
Also the Link-Icon shows as it always did in the Plugin.
![grafik](https://user-images.githubusercontent.com/32352291/34151204-dbfbca26-e4aa-11e7-8624-fb7070c700d5.png)

First problem when I click on a link: 
![grafik](https://user-images.githubusercontent.com/32352291/34150752-97afacb2-e4a9-11e7-9435-2a12b8ca3e42.png)

The link is as it was in the Plugin with file:///G:/.....

I thought I would get right back to you as this might be a simple problem I have over looked.

**Comment by AWolf81** [comment]
@PeterZamudio 
Have you installed the windows app that's required for the webextension? You can find the download link of the app after clicking on Addonbar icon and then `Show Installation guide`.

After installing the app the extension should work. The installation should work with-out admin rights if you already have VisualStudio redistributable on your machine. (If you need that, you need admin rights.)

**Comment by PeterZamudio** [comment]
@AWolf81
Bingo, its working now. Thanks.
Ill try it out and get back to you tomorrow. :-)

**Comment by AWolf81** [comment]
@AZimmerhofer I think it's required to unzip the files to a location at your pc and then temporarily install the `manifest.json` file.

**Comment by AZimmerhofer** [comment]
@AWolf81 
Thanks! It works! Special characters (äöüß) in file names lead to errors (Unexpected error).

**Comment by PeterZamudio** [comment]
Hello all.
Its working well by me, just as I need it. I can comfirm what AZimmerhofer said that all links with Special characters (äöüß) do not work. If that is the only problem I can get around that OK. I will keep test it and report any problems.

**Comment by GitHubTW** [comment]
Hi!

AWolf81, you are the developer of this add on? Thank you very much for developing and updating it to use with firefox version 57+!!!

I just installed local_filesystem_links-0.99.57-RC1.zip as a temporary add on.
But before being able to install it (error "... does not contain a valid install manifest..."), I had to change the extension from zip to xpi.
After installing the native app (having also an error message or a warning which I can not remember in detail) it works as expected on my windows 7 machine.

Thanks!
Thomas

**Comment by AWolf81** [comment]
@GitHubTW Thanks for your feedback and testing.
Yes, I'm doing most of the coding at the moment. 

Good to know that the package needs the xpi file ending. I've also had the problem with the manifest file if I directly wanted to load the zip-file.

Right now I'm a bit stuck with the Python part for opening files with special characters. I've made some progress but it's still not working. Maybe I'm creating a question for this at Stackoverflow. It's almost working but the problem is at the file exists check with the right encoding.

I think it would be OK to publish the extension as it is now because only special characters (like á, é, ü, ö, etc.) are still not working. But I'm trying to fix that with-in this week. 

The mentioned warning is probably like in the screenshot above and telling that the author of the extension is unknown. Signing is still on the todo-list but it's difficult with-out paying for a code signing certificate. If you're having a tip for code signing please let me know.

**Comment by GitHubTW** [comment]
@AWolf81 
I would prefer to have a published version as soon as possible because I do not use any special characters in the links or filenames.
Regarding signing I can not help! I don't even know what that is in detail!  :-(

**Comment by suetsugu1** [comment]
@AWolf81
Thank you. It is amazing.
However, if the file name contains Chinese characters, it fails (Unexpected error).
Chinese characters are not special characters for Japanese.

I hope these will also be successful in the new version.

**Comment by therouv** [comment]
@AWolf81 Any updates on this? I can confirm the previously mentioned behavior that clicking on links with umlauts or special characters lead to an error.

Besides that: Is there any way to donate to you guys for your excellent work?

**Comment by feinstaub** [comment]
> Besides that: Is there any way to donate to you guys for your excellent work?

Until some day, it was possible to donate for the addon on the Mozilla addon page which sent money to Mozilla. But the donate button has vanished. Don't know why. I did not setup a micropayment system for myself yet. Does anyone knows anything good without too much transaction fee? I would like to use something like GNU Taler https://taler.net some day.

Until then, if you like to support me, you can do that indirectly by donating money or work to a charitable organization that helps with environmental issues, global fairness, human rights issues or advocates for animal welfare (especially lifestock animals and fishes). And then report back (public or private) what you chose so that people can praise you :).

**Comment by AWolf81** [comment]
@therouv No much progress yet, sorry. I'm a bit stuck at the Python script but I'm pretty close to finish the unicode issue for opening links with "special" chars. Everything that was outside ASCII code can't be opened (so just English is fully supported). 
This needs to be fixed before releasing the new version as other languages will require unicode support (e.g. Chinese characters).

I don't know taler.net and I'm not sure if and how it's working. But you could send me money with Paypal.me [https://www.paypal.me/awlf81](https://www.paypal.me/awlf81). 
(You'll need a Paypal account for this. Sending & Receiving money is with-out a fee. Just currency exchanges are charged - so Euro is with-out fee.)

If there are any better donation service providers please let me know.
The donated money will be used for signing the native app - so anybody is welcome to donate. As soon there is enough money I'll check where to buy the code cert.
So we can remove the annoying warning for Windows users.

@feinstaub I agree with you. Your mentioned organizations should be supported but it's just indirectly supporting the development of the extension. Here is also a nice [post](https://opensource.com/life/11/10/should-you-donate-open-source-projects) about the topic.

So in my opinion direct donations are better and will help to improve the extension.

**Comment by AWolf81** [comment]
I have good news - the extension now fully supports unicode in file names. (If there are any issues please let me know.)

Tested with Chinese characters as well. Used 新年快乐 新年快樂 - should be Happy New Year in Chinese (https://www.chinahighlights.com/travelguide/special-report/chinese-new-year/happy-new-year-in-chinese.htm)
European accents (áàèé...) and umlaut (äöü...) are also working.

![Webextension unicode example](https://i.imgur.com/Ps4pfOb.gif)

Next I need to check the Linux version of the native app. The current version of the extension 0.99.57-RC2 can be downloaded [here](https://drive.google.com/file/d/1UV_A938RWg3deMsVLCrzOXQhBDnBuKt_/view?usp=sharing) for testing with **Windows**. (Linux is in progress.)

@feinstaub The native host binaries are now available in a separate repo (Windows only at the moment, Linux not ready yet). Please have a look [here](https://github.com/AWolf81/webextension_local_filesystem_links-native-host-binaries). (I've already updated the windows installer in `installed.html` to the new location)
Can you please check how signing is working? Is it possible with `web-ext sign` and your amo credentials?

I had problems with Google drive caching the old version of my installer that's why I decided to create a repo for the binaries.

Things that I have to do before releasing to Mozilla gallery:
- [ ] Improve & test Linux Python script and installer. (I think we need an installer now as there is an additional dependency (pathlib2) that's needed for unicode to work - it should be possible with [cxfreeze](https://cx-freeze.readthedocs.io/en/latest/).
- [ ] Update the CHANGELOG and create the release tag 0.99.57

**Comment by AZimmerhofer** [comment]
@AWolf81
I checked the new version - THANKS. Umlauts are working now!

**Comment by feinstaub** [comment]
Hi, I had to do some fixes before the signing came to this result (error message see README.md):

https://github.com/feinstaub/webextension-local-filelinks-prototype/commit/e29bd8591374658b5edf3960144507274e12bf06

**Comment by AWolf81** [comment]
OK, these problems should be correct in master. _locales folder is inside root directory in dist folder and no comments in locales json files. Version in manifest.json is also available.

Can you please try if it's possible to sign the extension in dist folder?
So create the extension like following in master:

0. `npm install` - install dependencies (just if you haven't done before)
1. `npm run build` - generates the production version of the extension in dist folder
2. `npm run bundle` - generate the bundle in web-ext-artifacts folder
3. `node node_modules/web-ext/bin/web-ext sign -s web-ext-artifacts/local_filesystem_links-0.99.57.zip --api-key ... --api-secret ...` this should sign the extension bundle - just not sure if it's working with the source (-s) parameter pointing to the bundle.

**Comment by feinstaub** [comment]
> So create the extension like following in master

Which repo? This one or the prototype?

> How is the publishing working? You have to upload the xpi bundle to Mozilla upload page, right? I haven't done that before and I just want to know.

The last times I did the publishing, I had to upload the xpi bundle which was then checked automatically.

**Comment by feinstaub** [comment]
> So create the extension like following in master

Which repo? This one or the prototype?

> How is the publishing working? You have to upload the xpi bundle to Mozilla upload page, right? I haven't done that before and I just want to know.

The last times I did the publishing, I had to upload the xpi bundle which was then checked automatically.

**Comment by AWolf81** [comment]
Yes, this repo. I haven't done anything at the prototype for a while and I think I'll mark the prototype as discontinued as the extension here is a lot better.

**Comment by PeterZamudio** [comment]
Hello all
I have tried to test it but my Antivirus Bitdefender will not let it pass. 
atc4.detection on local-link-messaging-host.exe
![grafik](https://user-images.githubusercontent.com/32352291/34671440-e6133a46-f47a-11e7-8cd5-ceb1fbb8d08e.png)
I have tried all the whitelisting and Ignoring settings but it still blocks. Ill keep at it and try to get around it. Please make sure that no Virus has slipped in.
Thank you for all your great work. I will be glad to help with the funds. Hope we get to our goal.

**Comment by therouv** [comment]
@AWolf81 Umlauts are working fine now. Thank you! :-)

Is it possible that you can add support for parentheses and ampersand as well? Currently this leads to an error (An unexpected error occurred).

**Comment by AWolf81** [comment]
@PeterZamudio Thanks for reporting this. I think this is a false positive and you could scan the file at VirusTotal (see link below) to check that is free of a virus. Your mentioned behavior is also mentioned [here](https://resource.dopus.com/t/bitdefender-dopus-exe-malware-gen-atc4-detection/26367).  You then can add the file to the white-list of Bitdefender (after checking that the hash values are matching, see below) and then it should work.
I don't have another solution as I'm not finding much at Google about the mentioned Virus.

I've downloaded the file from Github, installed it and checked it with Avira AntiVir Pro at my machine with-out any issues. I've also scanned the file at [virus total](https://www.virustotal.com/de/file/a3fdf5c83ddd0e15ab96eae95ab3cf20dee1fa24a4b981af91a78ff3c1de1769/analysis/1515444186/). And 6 from 65 anti virus scanners are telling that something is not right - Bitdefender there is with-out error. So most scanners are reporting no issues.

To be able to check that your downloaded file is matching the file hosted on Github I'll add MD5 and SHA1 hash values to the download page. You can download a Windows tool from [here](https://www.microsoft.com/en-us/download/details.aspx?id=11533) and run `fciv -add native-app-setup.exe -both` once the file fciv is in your path. If you don't like to install a tool you can also use the Windows tool `certutil` that should be available by default and can be used like following: `certutil -hashfile native-app-setup.exe MD5` or `certutil -hashfile native-app-setup.exe SHA1`.

This will show MD5 and SHA1 hash values. The hash values for the **installer** are:
~~~
// File Checksum Integrity Verifier version 2.05.
//
                MD5                             SHA-1
-------------------------------------------------------------------------
08a49447f951c22fcef85c640b13ea95 6499d8e9b85500c2d23ba7b9fc2f88c8c7166fe9 native-app-setup.exe (version 0.1.1.0)
~~~

The MD5 / SHA1 for local-file-messaging-host.exe (version 0.1.1.0) is:
~~~
// File Checksum Integrity Verifier version 2.05.
//
                MD5                             SHA-1
-------------------------------------------------------------------------
1638cc43528a001f571f2f258ee60599 1f4cca21104240da1fae36e2c32413dcd208c943 local-link-messaging-host.exe (version 0.1.1.0)
~~~

**Comment by AWolf81** [comment]
@therouv You're welcome.

I'll check if the issue with braces () and ampersand & can be fixed. Not sure what's wrong here but I'll have a look. On what system have you detected the issue? Windows or Linux?

But maybe this will be added in a future release. As we're planning to publish the extension like it is at the moment.

I also think that this requires only a fix in the host application - so a later update with-out updating the extension should be possible.

**Comment by therouv** [comment]
@AWolf81 Thanks for your reply. It's a Windows system.

**Comment by PeterZamudio** [comment]
@AWolf81 Thankyou for your help. It's up and running now and Umlauts are also working fine too. I will continue testing but I think it is perfect for us now. Hope you can get the setup and the Windows code signing certificate soved soon. Let me know where you need some funding, maybe with Paypal?

**Comment by AWolf81** [comment]
@PeterZamudio No problem.

I've added a Paypal funding link to the readme [here](https://github.com/feinstaub/webextension_local_filesystem_links/blob/master/README.md#donations). Donations of any size are welcome and please let me know if something is not working with the Paypal link (it's newly created).

First funding target is around 100 Euro then I'll order the certificate as mentioned [here](https://github.com/feinstaub/webextension_local_filesystem_links/issues/100). I haven't found anything cheaper than certum.pl, first signing is a bit more expensive because of the hardware that's needed for signing but the following years are cheaper.

At the moment, I'm working at the MacOS version 10.12 (Sierra) of the native app. But it's not ready yet. It took some time to get the virtual machine up and running (still some issues with the keyboard layout) but development environment is ready.

**Comment by PeterZamudio** [comment]
@AWolf81 OK Thanks, you are halfway there with your first target. I hope the other testers will do the rest.
Good luck.

**Comment by suetsugu1** [comment]
@AWolf81
In the new version, my Chinese characters folder also works well.
Thank you very much.

**Comment by AWolf81** [comment]
The version 0.99.57 with Firefox Quantum support is released today and available in Mozilla store.

I think we can close this now. If there are any issues, please feel free to create a new issue.

I'll create a new issue for the quarantine issue as @PeterZamudio mentioned because I've got a similar message today. Avira has found HEUR/APC (Cloud) signature.
